### ISSUE TITLE
Remove single "Deploy your own zkEVM on Goerli Testnet"

### ISSUE THREAD

**Issue by DannyS03** [0xPolygon/wiki#137] opened 2023-10-06 08:26 UTC
[This PR](https://github.com/0xPolygon/wiki/pull/73/commits/b0fa3d86c9b882eab178ecb6bd788304b6b90dfa#) which updated material for deploying a zkEVM instance on the Goerli testnet, was not captured when the main document was split into multiple documents.

We should remove [this](https://github.com/0xPolygon/wiki/blob/main/docs/zkevm/setup-zkevm.md).

**Comment by EmpieichO** [comment] 2023-10-06 17:03
Merging this new [PR](https://github.com/0xPolygon/wiki/pull/141) ... should solve this issue.

**Comment by EmpieichO** [comment] 2023-10-10 19:07
This PR https://github.com/0xPolygon/wiki/pull/141 was merged with no conflicts. The issue is resolved. Let's close @DannyS03

**Closed** 2023-10-12 22:36 UTC
Labels: zk:zkevm
